const mongoose = require('mongoose');
const ProfileSchema = new mongoose.Schema({
    //every profile is associated with user
    user:{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'user'
    },
    roll_no:{
        type:Number,
        required: true
    },
    batch:{
        type:Number,
        required: true
    },
    degree:{
        type:String,
        required:true
    },
    department:{
        type:String,
        required: true
    },
    company:{
        type:String
    },
    website:{
        type:String
    },
    location:{
        type:String
    },
    status:{
        type:String,
        required:true
    },
    skills:{
        type:[String],
        required: true
    },
    bio:{
        type:String
    },
    githubusername:{
        type:String
    },
    experience:[
        {
            title:{
                type:String,
                required:true
            },
            company:{
                type:String,
                required:true
            },
            location:{
                type:String,
                required:true
            },
            from:{
                type:Date,
                required:true
            },
            to:{
                type:Date,
            },
            current:{
                type:Boolean,
               default:false
            },
            description:{
                type:String,
            }
        }
    ],
    education:[{
        school:{
            type:String,
            required: true
        },
        location:{
            type:String,
            required:true
        },
        fieldofstudy:{
            type:String,
            required:true
        },
        from:{
            type:Date,
            required:true
        },
        to:{
            type:Date,
            required:true
        },
        description:{
            type:String
        }
    }],
    social:{
        youtube:{
            type:String
        },
        twitter:{
            type:String
        },
        facebook:{
            type:String
        },
        linkedin:{
            type:String
        },
        instagram:{
            type:String
        }
    },
    date:{
        type:Date,
        default:Date.now
    }
});

module.exports=Profile=mongoose.model('profile',ProfileSchema);